apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: argocd2
  template:
    metadata:
      labels:
        app: argocd2
    spec:
      containers:
      - name: myapp
        image: zertyr/argocd2:7105c433d7943b2ee336739e1970d31172d43959
        ports:
        - containerPort: 80

        apiVersion: apps/v1