name: Registry Docker

on:
  push:
    branches:
      - main
env:
  REGISTRY_URL: "docker.io"
  
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: check url
      run: echo ${{ env.REGISTRY_URL }}

    - name: Connexion au registre Docker
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin ${{ env.REGISTRY_URL }}

    - name: Obtenir la date et l'heure actuelles
      run: |
        export CURRENT_DATETIME=$(date '+%Y%m%d%H%M%S')

    - name: Afficher la valeur current datetime
      run: echo "${{ $CURRENT_DATETIME }}"

    - name: Construction de l'image Docker
      run: docker build -t argocd2:$CURRENT_DATETIME .

    - name: Exécution du conteneur Docker
      run: docker run -p 8080:80 argocd2:$CURRENT_DATETIME

    - name: Tag de l'image Docker
      run: docker tag argocd2:$CURRENT_DATETIME ${REGISTRY_URL}/argocd2:$CURRENT_DATETIME

    - name: Push de l'image Docker vers le registre
      run: docker push ${REGISTRY_URL}/argocd2:$CURRENT_DATETIME
